In [1]:
import numpy as np
import torch
from ultralytics import YOLO
from code_programm.path import get_path_weight_model
import pandas as pd
import os
import torch
import cv2
from torchvision.datasets import ImageFolder
import torchvision.transforms as transform

In [2]:
print(torch.cuda.device_count())
print(torch.cuda.get_device_name())
model = YOLO(get_path_weight_model('best_v2_n.pt'))

1
NVIDIA GeForce GTX 1080 Ti

In [3]:
wheel_ets_train_x = pd.DataFrame(columns=[i for i in range(128*128)])

In [4]:
path = [r'D:\Dataset_for_autopilot\2024-03-29 07-01-32',
        r'D:\Dataset_for_autopilot\2024-03-29 06-57-45']

In [5]:
os.path.join(r'D:\Dataset_for_autopilot\2024-03-29 07-04-10', f'road')

'D:\\Dataset_for_autopilot\\2024-03-29 07-04-10\\road'

In [6]:
model = YOLO(get_path_weight_model('best_v2_n.pt'))
for i in path:
    path_i = os.path.join(i, f'road')
    if os.path.exists(f'{path_i}') and os.path.isdir(f'{path_i}'):
        png_files = [os.path.join(path_i, file) for file in os.listdir(path_i) if file.endswith('.png')]
        print("Полные пути к файлам в папке:")
        for file_path in png_files:
            print(file_path)
    else:
        print("Указанный путь не существует или не является папкой.")
    
    size = 512
    combined_mask = np.zeros((size, size))    
    for file in png_files:
        results = model(file, imgsz=512, conf=0.65, show=False, device='cuda')
    
        combined_mask -= combined_mask * 0.5
    
        if results[0].masks is not None:
            for i in results[0].masks.data:
                combined_mask += i.cpu().numpy()
        new_image = cv2.resize(combined_mask, (128, 128))
        new_index = len(wheel_ets_train_x)
    
        # Добавьте новую строку в DataFrame с использованием метода loc
        name = file.split(f'\\')[-1].replace('.png', '')
        wheel_ets_train_x.loc[name] = new_image.flatten()

Полные пути к файлам в папке:
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685051.2301686.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685051.551114.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685051.8262064.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685052.1083193.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685052.3903449.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685052.6736522.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685052.960122.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685053.240664.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685053.5326562.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685053.819649.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685054.1086936.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685054.3906968.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685054.6696982.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685054.9566984.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685055.2316968.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685055.5196984.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685055.7996984.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685056.069698.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685056.3496974.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685056.618708.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685056.8897226.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685057.1697145.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685057.4587188.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685057.7407155.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685058.018721.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685058.2856379.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685058.5706391.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685058.8606396.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685059.137642.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685059.4276485.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685059.7108254.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685059.996639.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685060.2806478.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685060.566643.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685060.848651.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685061.132697.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685061.417646.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685061.6916378.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685061.967189.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685062.2344434.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685062.5062137.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685062.7802181.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685063.0618331.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685063.3339314.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685063.6039658.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685063.8829844.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685064.1572642.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685064.453187.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685064.7480745.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685065.0512373.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685065.3253946.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685065.6111627.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685065.8902788.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685066.1762793.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685066.4692776.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685066.7602782.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685067.0572803.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685067.3532784.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685067.6482787.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685067.929279.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685068.2112799.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685068.4942865.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685068.7832882.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685069.063295.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685069.3773918.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685069.6649525.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685069.9510348.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685070.272215.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685070.751316.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685071.0306501.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685071.3138347.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685071.606652.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685072.029546.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685072.3177695.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685072.6003048.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685072.8903913.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685073.1851504.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685073.5131595.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685073.8003862.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685074.086221.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685074.3862774.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685074.683275.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685074.9627097.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685075.2467084.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685075.5269434.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685075.817732.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685076.0978396.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685076.3813674.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685076.665368.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685076.9593718.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685077.2503674.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685077.530367.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685077.8153718.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685078.103383.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685078.4104972.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685078.7114954.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685079.0104961.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685079.3027933.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685079.6067955.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685079.9017942.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685080.1927645.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685080.4953651.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685080.7897692.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685081.0935802.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685081.3976495.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685081.7078.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685082.0154645.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685082.3112237.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685082.6113267.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685082.9079087.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685083.2111967.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685083.5113385.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685083.813665.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685084.1073432.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685084.4725502.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685084.7742362.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685085.078262.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685085.3666677.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685085.6506689.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685085.9326687.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685086.2178292.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685086.5018315.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685086.80183.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685087.0858314.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685087.3840086.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685087.6740084.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685087.9650068.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685088.2491467.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685088.539151.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685088.8361478.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685089.1441486.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685089.4426625.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685089.740661.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685090.0436552.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685090.3326402.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685090.6106524.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685090.9011827.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685091.1790314.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685091.4666424.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685091.740684.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685092.0189526.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685092.308165.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685092.592666.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685092.8744674.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685093.1572456.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685093.4471626.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685093.7573483.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685094.0515628.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685094.363838.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685094.6462407.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685094.9272594.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685095.211258.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685095.5022566.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685095.7914085.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685096.0744097.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685096.3585558.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685096.665763.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685096.9406598.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685097.2294924.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685097.5084946.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685097.7944932.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685098.0924938.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685098.3766577.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685098.661656.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685098.944656.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685099.2356567.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685099.5276568.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685099.8106565.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685100.1106586.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685100.4120355.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685100.6946688.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685100.9760888.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685101.261091.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685101.5453663.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685101.8363926.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685102.1256647.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685102.416228.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685102.6972463.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685102.9832842.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685103.2642193.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685103.566442.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685103.8504407.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685104.134442.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685104.441444.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685104.7312722.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685105.0098498.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685105.2892601.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685105.579257.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685105.8622577.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685106.1472561.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685106.4313295.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685106.7075508.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685106.993549.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685107.2758558.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685107.5594974.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685107.8493521.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685108.124353.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685108.4053526.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685108.685872.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685108.9718723.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685109.2508702.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685109.5170307.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685109.7870293.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685110.0680292.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685110.353031.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685110.6427624.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685110.927677.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685111.2122638.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685111.4970431.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685111.7806745.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685112.070237.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685112.3784485.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685112.6808317.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685112.9793403.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685113.280497.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685113.5985425.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685113.8925078.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685114.193786.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685114.4931643.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685114.7944672.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685115.0933104.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685115.3913236.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685115.6834497.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685115.9676323.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685116.2606325.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685116.547633.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685116.8306334.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685117.1236331.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685117.4207165.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685117.7167182.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685117.9977164.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685118.2817166.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685118.5667174.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685118.849717.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685119.1290894.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685119.4140987.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685119.8142815.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685120.0952818.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685120.3812041.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685120.664204.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685121.0541935.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685121.3496704.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685121.6347067.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685121.9338934.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685122.2167583.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685122.506295.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685122.8464415.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685123.1470883.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685123.436249.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685123.7308748.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685124.0304742.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685124.3132992.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685124.5946944.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685124.8841949.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685125.1631954.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685125.4503887.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685125.7443879.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685126.0333874.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685126.3123882.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685126.5943873.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685126.8813875.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685127.1605392.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685127.4485388.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685127.7305372.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685128.017539.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685128.3255394.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685128.6010184.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685128.87441.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685129.1563873.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685129.4393957.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685129.7193856.png
image 1/1 D:\Dataset_for_autopilot\2024-03-29 07-04-10\road\1711685051.2301686.png: 512x512 3 markup_lines, 7.2ms
Speed: 2.0ms preprocess, 7.2ms inference, 238.2ms postprocess per image at shape (1, 3, 512, 512)


In [7]:
len(wheel_ets_train_x)

1122

In [8]:
wheel_ets_train_x.to_csv(r'C:\PycharmProjects\ETS_Autopilot\dataset_for_wheel_nn\X_train_road_128_128.csv', index=False)

In [9]:
wheel_ets_train_y = pd.DataFrame(columns=['value'])

In [10]:
paths = [r'D:\Dataset_for_autopilot\2024-03-29 07-01-32',
        r'D:\Dataset_for_autopilot\2024-03-29 06-57-45']

In [11]:
for path in paths:
    # Открываем файл для чтения
    with open(path, 'r') as file:
        # Читаем файл построчно
        for line in file:
            # Обрабатываем каждую строку
            wheel_ets_train_y.loc[line.strip().split(',')[0]] = [line.strip().split(',')[1]]

In [12]:
len(wheel_ets_train_y)

1122

In [13]:
wheel_ets_train_y.to_csv(r'C:\PycharmProjects\ETS_Autopilot\dataset_for_wheel_nn\y_train_wheel.csv', index=False)

In [14]:
wheel_ets_train_speed = pd.DataFrame(columns=['speed'])

In [15]:
path = [r'D:\Dataset_for_autopilot\2024-03-29 07-01-32',
        r'D:\Dataset_for_autopilot\2024-03-29 06-57-45']

In [16]:
os.path.join(r'D:\Dataset_for_autopilot\2024-03-29 07-04-10', f'speed')

'D:\\Dataset_for_autopilot\\2024-03-29 07-04-10\\speed'

In [20]:
model_speed = YOLO(get_path_weight_model('best.pt'))
for i in path:
    path_i = os.path.join(i, f'speed')
    if os.path.exists(f'{path_i}') and os.path.isdir(f'{path_i}'):
        png_files = [os.path.join(path_i, file) for file in os.listdir(path_i) if file.endswith('.png')]
        print("Полные пути к файлам в папке:")
        for file_path in png_files:
            print(file_path)
    else:
        print("Указанный путь не существует или не является папкой.")
    
 
    for file in png_files:
        results = model_speed(file, conf=0.65, show=False, device='cuda')
    
        detected_objects = results[0].boxes.cls.tolist()
        if len(detected_objects) > 0:
            speed = ''
            for obj in detected_objects:
                speed += fr'{int(obj)}'
            speed = int(speed.replace('\n', ''))
            print(speed)
        else:
            wheel_ets_train_speed.loc[name] = speed
        name = file.split(f'\\')[-1].replace('.png', '')
        wheel_ets_train_speed.loc[name] = speed

Полные пути к файлам в папке:
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685051.2301686.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685051.551114.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685051.8262064.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685052.1083193.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685052.3903449.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685052.6736522.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685052.960122.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685053.240664.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685053.5326562.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685053.819649.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685054.1086936.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685054.3906968.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685054.6696982.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685054.9566984.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685055.2316968.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685055.5196984.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685055.7996984.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685056.069698.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685056.3496974.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685056.618708.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685056.8897226.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685057.1697145.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685057.4587188.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685057.7407155.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685058.018721.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685058.2856379.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685058.5706391.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685058.8606396.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685059.137642.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685059.4276485.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685059.7108254.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685059.996639.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685060.2806478.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685060.566643.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685060.848651.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685061.132697.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685061.417646.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685061.6916378.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685061.967189.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685062.2344434.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685062.5062137.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685062.7802181.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685063.0618331.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685063.3339314.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685063.6039658.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685063.8829844.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685064.1572642.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685064.453187.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685064.7480745.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685065.0512373.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685065.3253946.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685065.6111627.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685065.8902788.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685066.1762793.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685066.4692776.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685066.7602782.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685067.0572803.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685067.3532784.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685067.6482787.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685067.929279.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685068.2112799.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685068.4942865.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685068.7832882.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685069.063295.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685069.3773918.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685069.6649525.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685069.9510348.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685070.272215.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685070.751316.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685071.0306501.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685071.3138347.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685071.606652.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685072.029546.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685072.3177695.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685072.6003048.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685072.8903913.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685073.1851504.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685073.5131595.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685073.8003862.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685074.086221.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685074.3862774.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685074.683275.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685074.9627097.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685075.2467084.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685075.5269434.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685075.817732.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685076.0978396.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685076.3813674.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685076.665368.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685076.9593718.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685077.2503674.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685077.530367.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685077.8153718.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685078.103383.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685078.4104972.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685078.7114954.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685079.0104961.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685079.3027933.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685079.6067955.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685079.9017942.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685080.1927645.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685080.4953651.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685080.7897692.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685081.0935802.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685081.3976495.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685081.7078.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685082.0154645.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685082.3112237.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685082.6113267.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685082.9079087.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685083.2111967.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685083.5113385.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685083.813665.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685084.1073432.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685084.4725502.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685084.7742362.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685085.078262.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685085.3666677.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685085.6506689.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685085.9326687.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685086.2178292.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685086.5018315.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685086.80183.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685087.0858314.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685087.3840086.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685087.6740084.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685087.9650068.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685088.2491467.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685088.539151.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685088.8361478.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685089.1441486.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685089.4426625.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685089.740661.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685090.0436552.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685090.3326402.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685090.6106524.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685090.9011827.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685091.1790314.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685091.4666424.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685091.740684.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685092.0189526.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685092.308165.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685092.592666.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685092.8744674.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685093.1572456.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685093.4471626.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685093.7573483.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685094.0515628.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685094.363838.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685094.6462407.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685094.9272594.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685095.211258.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685095.5022566.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685095.7914085.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685096.0744097.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685096.3585558.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685096.665763.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685096.9406598.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685097.2294924.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685097.5084946.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685097.7944932.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685098.0924938.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685098.3766577.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685098.661656.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685098.944656.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685099.2356567.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685099.5276568.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685099.8106565.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685100.1106586.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685100.4120355.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685100.6946688.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685100.9760888.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685101.261091.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685101.5453663.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685101.8363926.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685102.1256647.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685102.416228.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685102.6972463.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685102.9832842.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685103.2642193.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685103.566442.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685103.8504407.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685104.134442.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685104.441444.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685104.7312722.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685105.0098498.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685105.2892601.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685105.579257.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685105.8622577.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685106.1472561.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685106.4313295.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685106.7075508.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685106.993549.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685107.2758558.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685107.5594974.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685107.8493521.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685108.124353.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685108.4053526.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685108.685872.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685108.9718723.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685109.2508702.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685109.5170307.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685109.7870293.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685110.0680292.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685110.353031.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685110.6427624.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685110.927677.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685111.2122638.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685111.4970431.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685111.7806745.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685112.070237.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685112.3784485.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685112.6808317.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685112.9793403.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685113.280497.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685113.5985425.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685113.8925078.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685114.193786.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685114.4931643.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685114.7944672.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685115.0933104.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685115.3913236.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685115.6834497.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685115.9676323.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685116.2606325.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685116.547633.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685116.8306334.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685117.1236331.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685117.4207165.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685117.7167182.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685117.9977164.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685118.2817166.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685118.5667174.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685118.849717.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685119.1290894.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685119.4140987.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685119.8142815.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685120.0952818.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685120.3812041.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685120.664204.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685121.0541935.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685121.3496704.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685121.6347067.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685121.9338934.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685122.2167583.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685122.506295.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685122.8464415.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685123.1470883.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685123.436249.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685123.7308748.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685124.0304742.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685124.3132992.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685124.5946944.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685124.8841949.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685125.1631954.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685125.4503887.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685125.7443879.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685126.0333874.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685126.3123882.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685126.5943873.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685126.8813875.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685127.1605392.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685127.4485388.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685127.7305372.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685128.017539.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685128.3255394.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685128.6010184.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685128.87441.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685129.1563873.png
D:\Dataset_for_autopilot\2024-03-29 07-04-10\speed\1711685129.4393957.png

In [18]:
len(wheel_ets_train_speed)

1122

In [ ]:
wheel_ets_train_speed.to_csv(r'C:\PycharmProjects\ETS_Autopilot\dataset_for_wheel_nn\X_train_speed.csv', index=False)

In [21]:
wheel_ets_train_x.head(1)

,0,1,2,3,4,5,6,7,8,9,...,16374,16375,16376,16377,16378,16379,16380,16381,16382,16383
1711685051.2301686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1711685051.551114,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1711685051.8262064,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1711685052.1083193,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1711685052.3903449,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
wheel_ets_train_y.head(1)

                                value
1711685051.2301686   -0.0047607421875
1711685051.551114    -0.0047607421875
1711685051.8262064   -0.0020751953125
1711685052.1083193  0.001129150390625
1711685052.3903449  0.002105712890625

In [ ]:
wheel_ets_train_speed.head(1)

In [35]:
wheel_ets_train_speed

KeyError: -1